<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\layout_builder_fields\EntityOperations;

/**
 * Implements hook_entity_presave().
 */
function layout_builder_fields_entity_presave(EntityInterface $entity) {
  /** @var \Drupal\layout_builder_fields\EntityOperations $entity_operations */
  $entity_operations = \Drupal::classResolver(EntityOperations::class);
  $entity_operations->handlePreSave($entity);

}
